# Generated by Django 2.1.7 on 2019-04-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Énoncé', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_of_exercise', models.CharField(choices=[('R1', 'Fill in the Blank'), ('R2', 'Multi Option Format'), ('R3', 'writing'), ('R4', 'Correct the answer')], default='R1', max_length=1)),
                ('select_an_exercise', models.CharField(choices=[('E1', 'Exercise 1'), ('E2', 'Exercise 2'), ('E3', 'Exercise 3'), ('E4', 'Exercise 4')], default='E1', max_length=1)),
                ('exercise_level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Etudiant')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='acceder',
            field=models.ManyToManyField(through='polls.Membership', to='polls.Etudiant'),
        ),
    ]
