# Generated by Django 2.1.7 on 2019-04-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cours')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('coeficient', models.FloatField(blank=True, default=None, null=True)),
                ('Test_type', models.CharField(max_length=30)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Teacher')),
            ],
        ),
    ]
