# Generated by Django 2.1.7 on 2019-04-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_group_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_assignment',
            name='test',
        ),
    ]
