# Generated by Django 2.1.7 on 2019-04-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_group_assignment_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_assignment',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Test'),
            preserve_default=False,
        ),
    ]
